// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'match-empty'
  | 'match-missing-list'
  | 'match-summary'
  | 'match-title'
  | 'menu-import-package'
  | 'menu-match-kp'
  | 'menu-pipeline'
  | 'menu-root'
  | 'menu-status'
  | 'package-done'
  | 'package-invalid'
  | 'package-missing'
  | 'pipeline-empty'
  | 'pipeline-more'
  | 'pipeline-summary'
  | 'pipeline-title'
  | 'prefs-kutuphane-root'
  | 'prefs-kutuphane-root-hint'
  | 'prefs-title'
  | 'status-error'
  | 'status-no-root'
  | 'status-ok'
  | 'status-registry'
  | 'status-root-missing';
